/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.experiments.PriceObject

/**
* This is the main application entry point
* @author Sonu
* @version 0.0.1
*/
class App {

    String  getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        App app = new App()
        ItemList itemList = new ItemList()
        // List <Map> priceMap =  new PriceObject().priceMap
        println app.greeting
        itemList.list.each { println it ? it.toUpperCase() : 'UNKNOWN' }
        itemList.list.eachWithIndex { item, idx -> println "$idx : ${item ? item.toUpperCase() : 'UNKNOWN'}" }
        // println(new PriceObject().calculateFinalPrices())
        println(new PriceObject().filterByRegion('US'))
    }

}
